### ISSUE TITLE
Responsive Shop Not Loading

### ISSUE THREAD

**Issue by spreadshirtster** [spreadshirt/apps#4]
The responsive shop at http://spreadshirt.github.io/apps/ does not load. The tablomat loads just fine but the shop doesn't.

Shop partners are facing a lot of pain and horror trying to integrate spreadshirt into our shops and having them ready for mobile devices. I was hoping the responsive shop would solve the issue, but apparently you guys no longer do active development for it. Could you please have a look into the issue? It would be really helpful if we all could use the responsive shop and integrate it into our brand sites.

Thank you very much for your help.

**Comment by rik84** [comment]
+1
Come on, it's 2015 and spreadshirt still isn't responsive/mobile-friendly?!

**Comment by it-ony** [comment]
So for every shop there is right now a mobile friendly version deployed automatically. E.g. visit http://qa-premium.spreadshirt.de from a mobile device.

The Shop5 which is not loading is kind of deprecated as a different team at Spreadshirt started the implementation. There is an internal ticket assigned to our release manager to fix the deployment.

**Comment by it-ony** [comment]
We deployed the version again.
