### ISSUE TITLE
Tablomat language bug

### ISSUE THREAD

**Issue by anarchoi** [spreadshirt/apps#9]
I have reported this issue here last year: https://feedback.spreadshirt.net/forums/290701-seller-feedback-north-america-australia/suggestions/9918474-better-french-translation-for-tablomat

The issue is still not fixed. The Spreadshirt shop is set to use French language, but Tablomat is half in french and half english. I just took a screenshot that shows the problem: https://gyazo.com/e674e24a5f33084a0a7f2b6362f5cd1d

You need a FRENCH browser to reproduce the problem.
Live link to Tablomat: https://www.ni-dieu-ni-maitre.com/custom.php

When testing with an english language browser, Tablomat is fully in english.
When testing with a french language browser, Tablomat is half french and half english.

**Comment by it-ony** [comment]
Will be fixed with the next release. Est. next week.
